language: java

jdk:
  - openjdk14

sudo: false

env:
  global:
    - CODECOV_TOKEN="22c70a77-c217-4c92-bb90-39bff4751037"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      -79646307753@yande.ru
    on_success: never # default: change
    on_failure: always # default: always